backend:
  name: github
  branch: master
  repo: antondb/personal-website

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: false
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - { label: 'Recipe', widget: "relation", name: 'recipe', collection: 'recipe',  displayFields: ["name"], searchFields: ["name"], valueField: 'id'}
  - name: 'recipe'
    label: 'Recipe'
    folder: 'content/recipes'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    editor:
      preview: false
    fields:
      - { label: 'Recipe Name', name: 'name', widget: 'string' }
      - label: 'ingredients' 
        name: 'recipeIngredient' 
        widget: 'list'
        fields:
          - {label: ingredient, name: ingredient, widget: string}
          - {label: amount, name: amount, widget: string}
      - { label: 'Intro', name: 'intro', widget: 'markdown' }
      - { label: 'Description', name: 'recipeInstructions', widget: 'markdown' }
      - { label: 'Cook Time', name: 'cookTime', widget: 'string' }
      - { label: 'Method', name: 'cookingMethod', widget: 'string' }
      - { label: 'Food Catgory', name: 'recipeCategory', widget: 'string' }
      - { label: 'Yield', name: 'recipeYield', widget: 'string' }